version: '3.8'

services:
  database:
    image: postgres
    restart: always
    networks:
      - compose-bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DB_ACERT
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    image: acert-api
    networks:
      - compose-bridge
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: DB_ACERT
    depends_on:
      - database


networks:
  compose-bridge:
    driver: bridge