# Para push direto na master (segurança 'rules' desabilitada)

name: 'Push Master: Build, Test, Deploy DockerHub'

on:
  push:
    branches:
      - main

jobs:
  deploy_after_push_on_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Maven Clean
        run: mvn clean

      - name: Maven Build
        run: mvn compile

      - name: Maven Package
        run: mvn package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fabramattos
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-prod
          push: true
          tags: fabramattos/desafio_acert_api:latest
